#!/bin/bash
set -e

echo ">>> Удаляем пакеты (только если они есть)..."
PACKAGES=(
  bspwm sxhkd polybar picom
  hyprland waybar foot
  xdg-desktop-portal-hyprland
  grim slurp wl-clipboard
  rofi dmenu feh lxappearance
  alacritty kitty
  firefox chromium
  thunar thunar-volman file-roller gvfs gvfs-mtp
  mpv vlc xfce4-taskmanager
  bluez bluez-utils blueman
  pipewire pipewire-alsa pipewire-pulse pipewire-jack wireplumber pavucontrol
  neovim nano micro htop btop ranger
  ttf-dejavu ttf-liberation noto-fonts noto-fonts-cjk noto-fonts-emoji
  zsh lightdm lightdm-gtk-greeter lightdm-gtk-greeter-settings
  exa bat
)

for pkg in "${PACKAGES[@]}"; do
  if pacman -Qi "$pkg" &>/dev/null; then
    echo ">>> Удаляем: $pkg"
    sudo pacman -Rns --noconfirm "$pkg"
  else
    echo "Пропускаем (не установлен): $pkg"
  fi
done

echo ">>> Чистим конфиги..."
rm -rf ~/.config/{bspwm,sxhkd,polybar,picom,hypr}
rm -rf ~/.oh-my-zsh ~/.p10k.zsh
rm -f ~/.zshrc
rm -rf ~/Pictures/wallpapers

echo ">>> Удаляем Exodia темы, иконки, обои..."
sudo rm -rf /usr/share/themes/exodia* /usr/share/icons/exodia* /usr/share/backgrounds/exodia*

echo ">>> Возвращаем bash по умолчанию..."
chsh -s /bin/bash

echo ">>> Отключаем LightDM..."
sudo systemctl disable lightdm || true
if pacman -Qi lightdm &>/dev/null; then
  sudo pacman -Rns --noconfirm lightdm lightdm-gtk-greeter lightdm-gtk-greeter-settings
fi

echo ">>> Очистка завершена!"
echo "Перезагрузи систему: sudo reboot"
